### ISSUE TITLE
Does it support character models?

### ISSUE THREAD

**Issue by anananlisr** [theanine3D/source-engine-collision-tools#6]
Do you support character models? I feel the effect is very strange when I use it to generate character models. I'm not sure if it's a problem with my settings.

**Comment by theanine3D** [comment]
It does support character models. If you want the most automated method possible, not the best or cleanest but requiring the least work, try the Fractured Collision feature.  This one will let you control the amount of hulls that gets created, and will create a gap between them (of a size that you choose). This will work best for character models but might generate some strange shapes for the hulls. But it technically will work. Note that you still need to assign the correct vertex group to each hull after generating the mesh.

The other option is you use the regular "Generate Collision Mesh" feature but you do some manual editing afterward to merge hulls together. Go into Edit Mode (Tab key), go into Wireframe mode (Z key), then highlight a bunch of hulls that should be combined into one (like all the ones in the hand), and press M, and choose By Distance. This will merge vertices together in the hulls if they are touching. Now go back to Object Mode, and press the Force Convex button that comes with the addon. It will merge the now-connected hulls together. Do this repeatedly until you reduce the hull count enough - you should have roughly only 1 hull per body part (like 1 hull for the left upper arm, 1 hull for the left lower arm, etc) though that's a rough estimate.
