### ISSUE TITLE
Undoing after generating a collision mesh instantly crashes Blender.

### ISSUE THREAD

**Issue by ChimiChamo** [theanine3D/source-engine-collision-tools#8]
I'm using Blender 3.6, after generating a collision mesh and doing nothing else then undoing will cause blender to close instantly

**Comment by theanine3D** [comment]
This has been a known issue for a long time. Thanks for reminding me. I just pushed some code today that seems to have finally fixed it. Can you test the latest code and let me know if the issue is fixed for you? My own tests show no more crashing.

**Comment by ChimiChamo** [comment]
it does in fact no longer crash, swell
