### ISSUE TITLE
I separated the roof, the floor, the walls for a castle wall.

### ISSUE THREAD

**Issue by demonelectro** [theanine3D/source-engine-collision-tools#9]
I have separated the roof, the floor, the walls for a castle wall but still it does not do the physics as I would like I find myself with this concern

![image](https://github.com/user-attachments/assets/4a51414c-d9e1-47f7-8835-e1d619d5cc13)
n
![image](https://github.com/user-attachments/assets/8c8be5a0-5340-4872-82f3-31fba3948728)

![image](https://github.com/user-attachments/assets/152c8523-85a1-4ac0-ba34-309eb32c987d)

blend file : https://www.mediafire.com/file/z24zbyzjmvpj5x7/Castle_Gothique.blend/file

**Comment by demonelectro** [comment]
![image](https://github.com/user-attachments/assets/27cad64e-f1bb-47bc-9225-76504d80868e)
![image](https://github.com/user-attachments/assets/3e8b07ed-4d07-4b80-b1ed-0ffaba9d4ab6)

same thing for my tower for some reason idk its weird to be fair i tried separate the collision mesh into multiple meshes and convex them i tried to split up its weird

**Comment by demonelectro** [comment]
![image](https://github.com/user-attachments/assets/cdd74944-b344-4400-a3cc-00794bdd7910)
I think the problem comes from the fact that the tower has small protective walls, that's what's causing my concern if I don't do this part it seems to work as you said in the comments I've managed with cylinders or rather basic shapes indoors to have a nice physique but as soon as you have a tower with objects sticking out it doesn't seem to work anymore.

**Comment by demonelectro** [comment]
My discord : terresouris

**Comment by theanine3D** [comment]
I'm not really sure what you're doing wrong, because for me, the collision generated just fine when I used the Generate Collision Mesh button on your castle wall. Here's an example showing the roof. It does benefit a bit from increasing the Extrude Factor a bit  - the automatic estimate set by the Recommended Settings button doesn't appear to make it thick enough in this particular case.

![image](https://github.com/user-attachments/assets/91ae6e81-5590-42fb-a12c-67c778de2904)

Here's the wall collision - generated fine as well:
![image](https://github.com/user-attachments/assets/59d6b4e3-5c0b-4575-81e6-b773c326181b)

I didn't change any settings besides pressing Recommended Settings and then doubling or tripling the Extrude Factor to make the hulls thicker.
![image](https://github.com/user-attachments/assets/cedeb9c7-c4bc-4778-a498-d4cfc525964f)

**Comment by demonelectro** [comment]
collision generation and great it's not the worry to generate the collision on blender the worry is that even if I don't separate the different elements like (walls, ceiling, floor) the physics is not considered as Concave and Convex the collision on source engine from HLMV and not correct

![image](https://github.com/user-attachments/assets/08e2922b-a237-4147-b329-e0ec3612a0b8)

as you can see inside the green circles
the player can't move near the wall, that's my concern.

i would discuss that on discord with you it would be maybe a bit simplier to explain more the situation if you want


however i will try to increase the hulls thicker to see

**Comment by demonelectro** [comment]
![image](https://github.com/user-attachments/assets/8b78335b-411a-4adc-ba63-6b89ad097591)

**Comment by demonelectro** [comment]
![image](https://github.com/user-attachments/assets/77baab36-45ca-40b2-a89e-bb54c92bb696)
its worked this time i increased the value of extrude factor weird but

**Comment by demonelectro** [comment]
oh okay after testing i founded the issue

when extrude factor is low example 0.25 result a bad physic can't be correctly convex 
when extrude factor is like 0.80 if fix the issue

**Comment by theanine3D** [comment]
Nice, I'm glad you found the solution. Yes, hulls can not be too thin, or Source will consider them invalid and then it will try "forcing" them to be valid by merging them together with other hulls. That is why you were seeing this part below, after compiling:
![image](https://github.com/user-attachments/assets/bf262fd2-d34d-472c-87f5-b98edcef1631)
It is the result of the compiler trying to merge hulls together that originally weren't merged in your export from Blender.

The Recommended Settings button works in a majority of cases, but there are times like this, especially when working with very large pieces of terrain/buildings, where you need to increase the thickness yourself manually.

Another thing that can cause hulls being merged together when they shouldn't, is if you forgot to add $concave to your QC file. Make sure you also have $concave enabled in your model's QC file, but you probably already did that.
https://developer.valvesoftware.com/wiki/$collisionmodel

**Comment by demonelectro** [comment]
still remain one issue 

![image](https://github.com/user-attachments/assets/cd36146d-101b-4a64-b581-53e73723fbf8)

![image](https://github.com/user-attachments/assets/06b9b5f2-232b-4160-8894-2238931dc74c)

![image](https://github.com/user-attachments/assets/777c647d-6642-4844-802a-902310820eed)

as you can see i separated every parts of the tower as single mesh i did a physic and convex all of them i can't go inside the tower
and its becaus of the top part and maybe the cylinder in the middle for the stairs its so weird why when its separated its doing this
